[0m10:43:10.495533 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174DD4B4950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174DD35C4A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174DD4B7FB0>]}


============================== 10:43:10.503222 | 36327285-7685-468a-9fcf-35810002989c ==============================
[0m10:43:10.503222 [info ] [MainThread]: Running with dbt=1.9.2
[0m10:43:10.505223 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Guuh\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init dw_aventureworks', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:43:10.536831 [debug] [MainThread]: Starter project path: C:\Users\Guuh\Documents\repositorios\indicium-dev-adventure_works\env\Lib\site-packages\dbt\include\starter_project
[0m10:43:10.556830 [info ] [MainThread]: 
Your new dbt project "dw_aventureworks" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:43:10.557831 [info ] [MainThread]: Setting up your profile.
[0m11:02:43.552562 [info ] [MainThread]: Profile dw_aventureworks written to C:\Users\Guuh\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m11:02:43.554565 [debug] [MainThread]: Command `dbt init` succeeded at 11:02:43.553565 after 1173.25 seconds
[0m11:02:43.554565 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174DAB0F230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174DD2108F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174DD1E3320>]}
[0m11:02:43.555563 [debug] [MainThread]: Flushing usage events
[0m11:02:44.178947 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:03:09.451564 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016C81465A60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016C814669F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016C814679E0>]}


============================== 11:03:09.455563 | 72ffabcc-9dad-487a-bb53-25a672b82cf7 ==============================
[0m11:03:09.455563 [info ] [MainThread]: Running with dbt=1.9.2
[0m11:03:09.455563 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Guuh\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:03:09.473563 [info ] [MainThread]: dbt version: 1.9.2
[0m11:03:09.474565 [info ] [MainThread]: python version: 3.12.4
[0m11:03:09.474565 [info ] [MainThread]: python path: C:\Users\Guuh\Documents\repositorios\indicium-dev-adventure_works\env\Scripts\python.exe
[0m11:03:09.475565 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m11:03:09.756593 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m11:03:09.757593 [info ] [MainThread]: Using profiles dir at C:\Users\Guuh\.dbt
[0m11:03:09.757593 [info ] [MainThread]: Using profiles.yml file at C:\Users\Guuh\.dbt\profiles.yml
[0m11:03:09.758594 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Guuh\Documents\repositorios\indicium-dev-adventure_works\dbt_project.yml
[0m11:03:09.759593 [info ] [MainThread]: Configuration:
[0m11:03:09.759593 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m11:03:09.760594 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m11:03:09.760594 [info ] [MainThread]: Required dependencies:
[0m11:03:09.761594 [debug] [MainThread]: Executing "git --help"
[0m11:03:09.779593 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:03:09.779593 [debug] [MainThread]: STDERR: "b''"
[0m11:03:09.780594 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:03:09.780594 [info ] [MainThread]: Connection test skipped since no profile was found
[0m11:03:09.781594 [info ] [MainThread]: [31m2 checks failed:[0m
[0m11:03:09.782594 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "northwind", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!


[0m11:03:09.783596 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Guuh\Documents\repositorios\indicium-dev-adventure_works\dbt_project.yml> not found

[0m11:03:09.784594 [debug] [MainThread]: Command `dbt debug` failed at 11:03:09.784594 after 0.49 seconds
[0m11:03:09.784594 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016C8129F650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016C81924740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016CFB715BE0>]}
[0m11:03:09.785594 [debug] [MainThread]: Flushing usage events
[0m11:03:10.355407 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:04:28.117808 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B254C1D250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B254C1F530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2522B6D50>]}


============================== 16:04:28.122264 | ba781563-842a-4ceb-9754-0fe32e1ccb5c ==============================
[0m16:04:28.122264 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:04:28.123264 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Guuh\\Documents\\repositorios\\indicium-dev-adventure_works', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run --select stg_person__address', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:04:28.123264 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Guuh\Documents\repositorios\indicium-dev-adventure_works\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:04:28.124265 [debug] [MainThread]: Command `dbt run` failed at 16:04:28.124265 after 0.16 seconds
[0m16:04:28.125264 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B254E555B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B254CE5400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B254D8F770>]}
[0m16:04:28.125264 [debug] [MainThread]: Flushing usage events
[0m16:04:28.821573 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:49:28.823714 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012B0556ABD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012B0564BBC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012B0365BD40>]}


============================== 21:49:28.836405 | c62e0759-f64a-4ce9-ac4b-1bddd92a3e96 ==============================
[0m21:49:28.836405 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:49:28.838334 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Guuh\\Documents\\repositorios\\indicium-dev-adventure_works', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:49:28.840329 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Guuh\Documents\repositorios\indicium-dev-adventure_works\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:49:28.843336 [debug] [MainThread]: Command `dbt run` failed at 21:49:28.843336 after 0.17 seconds
[0m21:49:28.844333 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012B0564BBC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012B05A232C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012B05A6B9B0>]}
[0m21:49:28.846334 [debug] [MainThread]: Flushing usage events
[0m21:49:29.413676 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:49:44.739696 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A54E815E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A57ABDD30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A5709F3E0>]}


============================== 21:49:44.743696 | 7b06be73-7c38-49f6-a98d-54c7a7d4dd3f ==============================
[0m21:49:44.743696 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:49:44.743696 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Guuh\\Documents\\repositorios\\indicium-dev-adventure_works', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m21:49:44.744697 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Guuh\Documents\repositorios\indicium-dev-adventure_works\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:49:44.745699 [debug] [MainThread]: Command `dbt deps` failed at 21:49:44.745699 after 0.12 seconds
[0m21:49:44.746697 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A571253A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A5709F380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A54E815E0>]}
[0m21:49:44.746697 [debug] [MainThread]: Flushing usage events
[0m21:49:45.285916 [debug] [MainThread]: An error was encountered while trying to flush usage events
